Don't require the edited_at attribute.
The edited_at attribute is available only since Mastodon v3.5.0.

Fixes:

    $ zygolophodon https://a.gawlinski.com/@jeff/106599684741456770
    ...
    Traceback (most recent call last):
      File ".../zygolophodon", line 954, in <module>
        main()
      File ".../zygolophodon", line 947, in main
        xmain()
      File ".../zygolophodon", line 513, in xmain
        process_post(instance, post_id=match.ident,
      File ".../zygolophodon", line 863, in process_post
        print_post(post, hide_in_reply_to=with_ancestors)
      File ".../zygolophodon", line 909, in print_post
        if post.edited_at:
           ^^^^^^^^^^^^^^
    KeyError: 'edited_at'