Print post's account info only when available.
This info is missing for reblogged posts on Pleroma instances.

Fixes:

    $ zygolophodon https://pleroma.debian.social/users/wouter
    ...
    Location: https://fosstodon.org/users/fosdem/statuses/113794618957623693
    From: Wouter Verhelst <https://pleroma.debian.social/users/wouter>
    Date: 2025-01-08 20:36:43Z
    Reblog: yes

    Location: https://fosstodon.org/@fosdem/113794618957623693
    Traceback (most recent call last):
      ...
      File ".../zygolophodon", line 518, in print_post
        print_post(post.reblog)
      File ".../zygolophodon", line 510, in print_post
        print('From:', fmt_user(post.account))
                       ^^^^^^^^^^^^^^^^^^^^^^
      File ".../zygolophodon", line 178, in fmt_user
        return f'{account.display_name} <{fmt_url(account.url)}>'.lstrip()
                  ^^^^^^^^^^^^^^^^^^^^
    KeyError: 'display_name'