fmt_html(): fix handling empty URLs.
Fixes: commit a379b820e7801bf034a751edb66b007c1b7f527a

Fixes:

    $ zygolophodon https://mastodon.social/statuses/113956977571065159
    Location: https://shkspr.mobi/blog/2025/02/talking-contact-tracing-at-fosdem/
    ...
    Traceback (most recent call last):
      File ".../zygolophodon", line 934, in <module>
        main()
      File ".../zygolophodon", line 927, in main
        xmain()
      File ".../zygolophodon", line 498, in xmain
        process_post(instance, post_id=match.ident,
      File ".../zygolophodon", line 843, in process_post
        print_post(post, hide_in_reply_to=with_ancestors)
      File ".../zygolophodon", line 901, in print_post
        text = fmt_html(post.content)
               ^^^^^^^^^^^^^^^^^^^^^^
      File ".../zygolophodon", line 347, in fmt_html
        text = re.sub('\N{STX}(.*?)\N{ETX}|([\N{DC1}\N{DC2}])(\\w+)\N{ETX}', repl, text, flags=re.DOTALL)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
        return _compile(pattern, flags).sub(repl, string, count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../zygolophodon", line 345, in repl
        footnote = prefix + footnote
                   ~~~~~~~^~~~~~~~~~
    TypeError: can only concatenate str (not "NoneType") to str