Catch JSON decoding errors.
Before:

    $ zygolophodon kyva@luzeed.org
    Traceback (most recent call last):
      ... (26 lines of traceback)
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

After:

    $ zygolophodon kyva@luzeed.org
    zygolophodon: <https://luzeed.org/api/v1/accounts/lookup?acct=kyva>: received HTML instead of JSON