Fix printing posts with no URL.
Fixes:

    $ zygolophodon https://mastodon.social/@http@infosec.exchange
    ...
    Traceback (most recent call last):
      ...
      File ".../zygolophodon", line 461, in process_user
        fix_posts(statuses, domain)
      File ".../zygolophodon", line 435, in fix_posts
        fix_post(post, domain)
      File ".../zygolophodon", line 425, in fix_post
        match = re.fullmatch('https://([^/]+)/users/([^/]+)/statuses/([0-9]+)/activity', post.url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/re/__init__.py", line 171, in fullmatch
        return _compile(pattern, flags).fullmatch(string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: expected string or bytes-like object, got 'NoneType'

Fixes: commit c1f2238dc2bcd5bca3d89f6eca36703d86fb9529