Fix printing pinned posts.
Fixes: commit d6b45bae319e1b66d335c52959e4005797332a0c

Fixes:

    $ zygolophodon https://mastodon.social/@juliank
    ...
    Location: https://mastodon.social/@juliank/110073275258335460
    Traceback (most recent call last):
      ...
      File ".../zygolophodon", line 447, in process_user
        print_statuses(statuses, pinned=True)
      File ".../zygolophodon", line 491, in print_statuses
        print_post(post, pinned=pinned, hide_in_reply_to=hide_in_reply_to)
      File ".../zygolophodon", line 504, in print_post
        if post.in_reply_to_url and not hide_in_reply_to:
           ^^^^^^^^^^^^^^^^^^^^
    KeyError: 'in_reply_to_url'